-- =====================================================================
-- Gerenciador auditavel das regras De/Para
-- =====================================================================
--
-- Problema:
--   as regras por nome/CNPJ so podiam ser criadas na fila de excecoes. Para
--   corrigir uma regra existente era preciso encontra-la entre alteracoes
--   recentes, sem busca completa, impacto previo ou historico persistente.
--
-- Solucao:
--   - leitura protegida e paginada de todas as regras;
--   - pre-visualizacao transacional usando o fato_financeiro canonico;
--   - alteracao com chave imutavel, token otimista e ativacao/desativacao;
--   - auditoria central por trigger, incluindo as RPCs antigas;
--   - desfazer exato do ultimo estado compativel;
--   - refresh dos paineis pela fila assincrona existente.
--
-- Riscos controlados:
--   uma regra pode reclassificar varias transacoes vivas e tambem passa a
--   valer para importacoes futuras. Ajustes individuais continuam vencendo o
--   De/Para. raw_historico permanece congelado e nunca e sincronizado por esta
--   rotina. A previa e revertida dentro da propria transacao, sem persistir
--   dados ou auditoria; somente a confirmacao grava o novo estado.
-- =====================================================================

begin;

create table if not exists private.de_para_historico (
  id bigint generated by default as identity primary key,
  regra_id bigint not null,
  chave_tipo text not null,
  chave_valor text not null,
  acao text not null check (acao in ('criar', 'alterar', 'ativar', 'desativar', 'excluir')),
  origem_acao text not null default 'sistema',
  existia_antes boolean not null,
  fornecedor_antes text,
  categoria_antes text,
  ativo_antes boolean,
  atualizado_em_antes timestamptz,
  existia_depois boolean not null,
  fornecedor_depois text,
  categoria_depois text,
  ativo_depois boolean,
  atualizado_em_depois timestamptz,
  alterado_por uuid,
  alterado_em timestamptz not null default now(),
  desfeito_por uuid,
  desfeito_em timestamptz,
  check ((desfeito_por is null) = (desfeito_em is null)),
  check (
    existia_antes
    or (
      fornecedor_antes is null
      and categoria_antes is null
      and ativo_antes is null
      and atualizado_em_antes is null
    )
  ),
  check (
    existia_depois
    or (
      fornecedor_depois is null
      and categoria_depois is null
      and ativo_depois is null
      and atualizado_em_depois is null
    )
  )
);

create index if not exists ix_de_para_historico_regra
  on private.de_para_historico (regra_id, id desc);

create index if not exists ix_de_para_historico_chave
  on private.de_para_historico (chave_tipo, chave_valor, id desc);

alter table private.de_para_historico enable row level security;
revoke all privileges on private.de_para_historico
  from public, anon, authenticated;

comment on table private.de_para_historico is
  'Historico append-only das regras De/Para; exposto somente pela view protegida do gerenciador.';

create or replace function private.token_estado_de_para(
  p_id bigint,
  p_chave_tipo text,
  p_chave_valor text,
  p_fornecedor text,
  p_categoria text,
  p_ativo boolean,
  p_atualizado_em timestamptz
)
returns text
language sql
immutable
security invoker
set search_path = pg_catalog, pg_temp
as $function$
  select md5(
    jsonb_build_array(
      p_id,
      p_chave_tipo,
      p_chave_valor,
      p_fornecedor,
      p_categoria,
      p_ativo,
      extract(epoch from p_atualizado_em)
    )::text
  );
$function$;

revoke all privileges on function private.token_estado_de_para(
  bigint, text, text, text, text, boolean, timestamptz
) from public, anon, authenticated;

create or replace function private.auditar_de_para()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public
as $function$
declare
  v_contexto text := coalesce(
    nullif(current_setting('sirfisher.de_para_contexto', true), ''),
    'sistema'
  );
  v_acao text;
  v_regra_id bigint;
  v_chave_tipo text;
  v_chave_valor text;
  v_existia_antes boolean := false;
  v_fornecedor_antes text;
  v_categoria_antes text;
  v_ativo_antes boolean;
  v_atualizado_em_antes timestamptz;
  v_existia_depois boolean := false;
  v_fornecedor_depois text;
  v_categoria_depois text;
  v_ativo_depois boolean;
  v_atualizado_em_depois timestamptz;
begin
  -- A previa e o desfazer usam subfluxos controlados. A previa inteira e
  -- revertida; o desfazer ja marca o evento original com autor e horario.
  if v_contexto in ('preview', 'desfazer') then
    if tg_op = 'DELETE' then
      return old;
    end if;
    return new;
  end if;

  if tg_op <> 'INSERT' then
    v_regra_id := old.id;
    v_chave_tipo := old.chave_tipo;
    v_chave_valor := old.chave_valor;
    v_existia_antes := true;
    v_fornecedor_antes := old.fornecedor;
    v_categoria_antes := old.categoria;
    v_ativo_antes := old.ativo;
    v_atualizado_em_antes := old.atualizado_em;
  end if;

  if tg_op <> 'DELETE' then
    v_regra_id := new.id;
    v_chave_tipo := new.chave_tipo;
    v_chave_valor := new.chave_valor;
    v_existia_depois := true;
    v_fornecedor_depois := new.fornecedor;
    v_categoria_depois := new.categoria;
    v_ativo_depois := new.ativo;
    v_atualizado_em_depois := new.atualizado_em;
  end if;

  if tg_op = 'INSERT' then
    v_acao := 'criar';
  elsif tg_op = 'DELETE' then
    v_acao := 'excluir';
  elsif old.ativo is distinct from new.ativo then
    v_acao := case when new.ativo then 'ativar' else 'desativar' end;
  else
    v_acao := 'alterar';
  end if;

  insert into private.de_para_historico (
    regra_id,
    chave_tipo,
    chave_valor,
    acao,
    origem_acao,
    existia_antes,
    fornecedor_antes,
    categoria_antes,
    ativo_antes,
    atualizado_em_antes,
    existia_depois,
    fornecedor_depois,
    categoria_depois,
    ativo_depois,
    atualizado_em_depois,
    alterado_por,
    alterado_em
  ) values (
    v_regra_id,
    v_chave_tipo,
    v_chave_valor,
    v_acao,
    v_contexto,
    v_existia_antes,
    v_fornecedor_antes,
    v_categoria_antes,
    v_ativo_antes,
    v_atualizado_em_antes,
    v_existia_depois,
    v_fornecedor_depois,
    v_categoria_depois,
    v_ativo_depois,
    v_atualizado_em_depois,
    auth.uid(),
    clock_timestamp()
  );

  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$function$;

drop trigger if exists tr_auditar_de_para on public.de_para;
create trigger tr_auditar_de_para
after insert or update or delete on public.de_para
for each row execute function private.auditar_de_para();

revoke all privileges on function private.auditar_de_para()
  from public, anon, authenticated;

-- A gravacao passa exclusivamente pelas RPCs SECURITY DEFINER, inclusive na
-- fila de excecoes. Isso impede que a Data API contorne validacao e auditoria.
revoke insert, update, delete on table public.de_para
  from authenticated;
revoke usage, select on sequence public.de_para_id_seq
  from authenticated;
drop policy if exists de_para_auth_ins on public.de_para;
drop policy if exists de_para_auth_upd on public.de_para;
drop policy if exists de_para_auth_del on public.de_para;

create or replace view public.app_gerenciador_de_para
with (security_barrier = true, security_invoker = false) as
select
  d.id,
  d.chave_tipo,
  d.chave_valor,
  d.fornecedor,
  d.categoria,
  c.dre_grupo,
  c.natureza,
  d.ativo,
  d.atualizado_em,
  private.token_estado_de_para(
    d.id,
    d.chave_tipo,
    d.chave_valor,
    d.fornecedor,
    d.categoria,
    d.ativo,
    d.atualizado_em
  ) as estado_token
from public.de_para d
left join public.categoria_dre c
  on c.categoria = d.categoria
where public.usuario_pode_acessar_pagina('gerenciador_de_para.html');

comment on view public.app_gerenciador_de_para is
  'Estado atual das regras por nome/CNPJ, com chave imutavel e token otimista para o gerenciador De/Para.';

revoke all privileges on public.app_gerenciador_de_para
  from public, anon, authenticated;
grant select on public.app_gerenciador_de_para to authenticated;

create or replace function public.listar_regras_de_para(
  p_busca text default null,
  p_status text default 'ativas',
  p_categoria text default null,
  p_chave_tipo text default null,
  p_pagina integer default 1,
  p_tamanho_pagina integer default 30
)
returns jsonb
language plpgsql
stable
security definer
set search_path = pg_catalog, public
as $function$
declare
  v_busca text := nullif(btrim(p_busca), '');
  v_busca_digitos text := case
    when nullif(btrim(p_busca), '') ~ '[0-9]' then public.so_digitos(p_busca)
    else null
  end;
  v_status text := coalesce(nullif(btrim(p_status), ''), 'ativas');
  v_pagina integer := greatest(coalesce(p_pagina, 1), 1);
  v_tamanho integer := least(greatest(coalesce(p_tamanho_pagina, 30), 1), 100);
  v_resultado jsonb;
begin
  if not public.usuario_pode_acessar_pagina('gerenciador_de_para.html') then
    raise exception using errcode = '42501', message = 'Acesso nao autorizado.';
  end if;

  if v_status not in ('ativas', 'inativas', 'todas') then
    raise exception using errcode = '22023', message = 'Filtro de status invalido.';
  end if;

  if p_chave_tipo is not null and p_chave_tipo not in ('nome', 'cnpj') then
    raise exception using errcode = '22023', message = 'Tipo de chave invalido.';
  end if;

  with filtradas as materialized (
    select
      d.id,
      d.chave_tipo,
      d.chave_valor,
      d.fornecedor,
      d.categoria,
      c.dre_grupo,
      c.natureza,
      d.ativo,
      d.atualizado_em,
      private.token_estado_de_para(
        d.id,
        d.chave_tipo,
        d.chave_valor,
        d.fornecedor,
        d.categoria,
        d.ativo,
        d.atualizado_em
      ) as estado_token
    from public.de_para d
    left join public.categoria_dre c
      on c.categoria = d.categoria
    where (v_status = 'todas'
      or (v_status = 'ativas' and d.ativo)
      or (v_status = 'inativas' and not d.ativo))
      and (p_categoria is null or d.categoria = p_categoria)
      and (p_chave_tipo is null or d.chave_tipo = p_chave_tipo)
      and (
        v_busca is null
        or coalesce(d.fornecedor, '') ilike '%' || v_busca || '%'
        or d.chave_valor ilike '%' || v_busca || '%'
        or (
          d.chave_tipo = 'cnpj'
          and v_busca_digitos is not null
          and d.chave_valor ilike '%' || v_busca_digitos || '%'
        )
        or d.categoria ilike '%' || v_busca || '%'
      )
  ),
  pagina as (
    select f.*
    from filtradas f
    order by f.ativo desc, coalesce(f.fornecedor, f.chave_valor), f.id
    limit v_tamanho
    offset (v_pagina - 1)::bigint * v_tamanho::bigint
  )
  select jsonb_build_object(
    'itens', coalesce(
      (
        select jsonb_agg(
          jsonb_build_object(
            'id', p.id,
            'chave_tipo', p.chave_tipo,
            'chave_valor', p.chave_valor,
            'fornecedor', p.fornecedor,
            'categoria', p.categoria,
            'dre_grupo', p.dre_grupo,
            'natureza', p.natureza,
            'ativo', p.ativo,
            'atualizado_em', p.atualizado_em,
            'estado_token', p.estado_token
          )
          order by p.ativo desc, coalesce(p.fornecedor, p.chave_valor), p.id
        )
        from pagina p
      ),
      '[]'::jsonb
    ),
    'total_filtrado', (select count(*) from filtradas),
    'total_ativas', (select count(*) from public.de_para d where d.ativo),
    'total_inativas', (select count(*) from public.de_para d where not d.ativo),
    'pagina', v_pagina,
    'tamanho_pagina', v_tamanho
  ) into v_resultado;

  return v_resultado;
end;
$function$;

create or replace function public.prever_alteracao_de_para(
  p_id bigint,
  p_fornecedor text,
  p_categoria text,
  p_ativo boolean,
  p_estado_token_esperado text
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $function$
declare
  v_regra public.de_para%rowtype;
  v_fornecedor text := nullif(btrim(p_fornecedor), '');
  v_token_atual text;
  v_antes jsonb := '[]'::jsonb;
  v_depois jsonb := '[]'::jsonb;
  v_correspondencias bigint := 0;
  v_ajustes_manuais bigint := 0;
  v_classificacoes bigint := 0;
  v_rotulos bigint := 0;
  v_impactadas bigint := 0;
  v_entradas numeric := 0;
  v_saidas numeric := 0;
  v_data_min date;
  v_data_max date;
  v_transicoes jsonb := '[]'::jsonb;
begin
  if not public.usuario_pode_acessar_pagina('gerenciador_de_para.html') then
    raise exception using errcode = '42501', message = 'Acesso nao autorizado.';
  end if;

  if p_id is null or p_ativo is null or p_estado_token_esperado is null then
    raise exception using errcode = '22023', message = 'Estado da regra incompleto.';
  end if;

  if v_fornecedor is null or char_length(v_fornecedor) > 120 then
    raise exception using errcode = '22023',
      message = 'O nome de exibicao e obrigatorio e deve ter ate 120 caracteres.';
  end if;

  if not exists (
    select 1 from public.categoria_dre c where c.categoria = p_categoria
  ) then
    raise exception using errcode = '22023', message = 'Categoria invalida.';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(58000002::bigint);

  select d.*
  into v_regra
  from public.de_para d
  where d.id = p_id
  for update;

  if not found then
    raise exception using errcode = 'P0002', message = 'Regra De/Para nao encontrada.';
  end if;

  v_token_atual := private.token_estado_de_para(
    v_regra.id,
    v_regra.chave_tipo,
    v_regra.chave_valor,
    v_regra.fornecedor,
    v_regra.categoria,
    v_regra.ativo,
    v_regra.atualizado_em
  );

  if v_token_atual is distinct from p_estado_token_esperado then
    raise exception using errcode = '40001',
      message = 'Esta regra mudou desde que a tela foi carregada. Atualize a lista e tente novamente.';
  end if;

  if row(v_regra.fornecedor, v_regra.categoria, v_regra.ativo)
       is not distinct from row(v_fornecedor, p_categoria, p_ativo) then
    raise exception using errcode = '22023', message = 'Nenhuma alteracao foi informada.';
  end if;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'origem', f.origem,
        'raw_id', f.raw_id::text,
        'data_caixa', f.data_caixa,
        'valor', f.valor,
        'categoria', f.categoria,
        'dre_grupo', f.dre_grupo,
        'status', f.status,
        'entra_dre', f.entra_dre,
        'fornecedor', f.fornecedor,
        'manual', a.id is not null,
        'fonte_token', md5(jsonb_build_array(
          f.data_caixa,
          f.valor,
          f.movimentacao,
          f.tipo,
          f.contraparte_nome,
          f.contraparte_doc
        )::text),
        'ajuste_token', case when a.id is null then null else md5(
          jsonb_build_array(a.categoria, a.criado_em, a.observacao)::text
        ) end
      ) order by f.origem, f.raw_id
    ),
    '[]'::jsonb
  )
  into v_antes
  from public.fato_financeiro f
  left join public.ajuste_manual a
    on a.origem = f.origem
   and a.raw_id = f.raw_id
  where f.origem <> 'historico'
    and (
      (
        v_regra.chave_tipo = 'cnpj'
        and f.contraparte_doc like '%/%'
        and f.contraparte_doc not like '%*%'
        and public.so_digitos(f.contraparte_doc) = v_regra.chave_valor
      )
      or
      (
        v_regra.chave_tipo = 'nome'
        and f.contraparte_nome is not null
        and f.contraparte_nome not ilike 'desconhecido'
        and public.normaliza_nome(f.contraparte_nome) = v_regra.chave_valor
      )
    );

  perform pg_catalog.set_config('sirfisher.de_para_contexto', 'preview', true);

  -- O erro proposital encerra a subtransacao e desfaz tanto o UPDATE quanto
  -- qualquer efeito do trigger. Variaveis PL/pgSQL mantem a fotografia lida.
  begin
    update public.de_para
    set fornecedor = v_fornecedor,
        categoria = p_categoria,
        ativo = p_ativo,
        atualizado_em = clock_timestamp()
    where id = v_regra.id;

    select coalesce(
      jsonb_agg(
        jsonb_build_object(
          'origem', f.origem,
          'raw_id', f.raw_id::text,
          'data_caixa', f.data_caixa,
          'valor', f.valor,
          'categoria', f.categoria,
          'dre_grupo', f.dre_grupo,
          'status', f.status,
          'entra_dre', f.entra_dre,
          'fornecedor', f.fornecedor,
          'manual', a.id is not null,
          'fonte_token', md5(jsonb_build_array(
            f.data_caixa,
            f.valor,
            f.movimentacao,
            f.tipo,
            f.contraparte_nome,
            f.contraparte_doc
          )::text),
          'ajuste_token', case when a.id is null then null else md5(
            jsonb_build_array(a.categoria, a.criado_em, a.observacao)::text
          ) end
        ) order by f.origem, f.raw_id
      ),
      '[]'::jsonb
    )
    into v_depois
    from public.fato_financeiro f
    left join public.ajuste_manual a
      on a.origem = f.origem
     and a.raw_id = f.raw_id
    where f.origem <> 'historico'
      and (
        (
          v_regra.chave_tipo = 'cnpj'
          and f.contraparte_doc like '%/%'
          and f.contraparte_doc not like '%*%'
          and public.so_digitos(f.contraparte_doc) = v_regra.chave_valor
        )
        or
        (
          v_regra.chave_tipo = 'nome'
          and f.contraparte_nome is not null
          and f.contraparte_nome not ilike 'desconhecido'
          and public.normaliza_nome(f.contraparte_nome) = v_regra.chave_valor
        )
      );

    raise exception using errcode = 'PZ001', message = 'rollback da previa';
  exception
    when sqlstate 'PZ001' then null;
  end;

  -- Importacoes e ajustes nao usam o lock do De/Para. Se algum deles mudar
  -- entre as duas fotografias, a previa e repetida em vez de atribuir essa
  -- concorrencia a regra simulada.
  if exists (
    with antes as (
      select *
      from jsonb_to_recordset(v_antes) as x(
        origem text,
        raw_id text,
        data_caixa date,
        valor numeric,
        categoria text,
        dre_grupo text,
        status text,
        entra_dre boolean,
        fornecedor text,
        manual boolean,
        fonte_token text,
        ajuste_token text
      )
    ),
    depois as (
      select *
      from jsonb_to_recordset(v_depois) as x(
        origem text,
        raw_id text,
        data_caixa date,
        valor numeric,
        categoria text,
        dre_grupo text,
        status text,
        entra_dre boolean,
        fornecedor text,
        manual boolean,
        fonte_token text,
        ajuste_token text
      )
    )
    select 1
    from antes a
    full join depois d
      on d.origem = a.origem
     and d.raw_id = a.raw_id
    where a.origem is null
       or d.origem is null
       or a.fonte_token is distinct from d.fonte_token
       or a.ajuste_token is distinct from d.ajuste_token
  ) then
    raise exception using errcode = '40001',
      message = 'Os lancamentos mudaram durante a previa. Revise o impacto novamente.';
  end if;

  with antes as (
    select *
    from jsonb_to_recordset(v_antes) as x(
      origem text,
      raw_id text,
      data_caixa date,
      valor numeric,
      categoria text,
      dre_grupo text,
      status text,
      entra_dre boolean,
      fornecedor text,
      manual boolean,
      fonte_token text,
      ajuste_token text
    )
  ),
  depois as (
    select *
    from jsonb_to_recordset(v_depois) as x(
      origem text,
      raw_id text,
      data_caixa date,
      valor numeric,
      categoria text,
      dre_grupo text,
      status text,
      entra_dre boolean,
      fornecedor text,
      manual boolean,
      fonte_token text,
      ajuste_token text
    )
  ),
  comparacao as (
    select
      coalesce(a.origem, d.origem) as origem,
      coalesce(a.raw_id, d.raw_id) as raw_id,
      coalesce(a.data_caixa, d.data_caixa) as data_caixa,
      coalesce(a.valor, d.valor) as valor,
      coalesce(a.manual, d.manual, false) as manual,
      a.categoria as categoria_antes,
      d.categoria as categoria_depois,
      a.status as status_antes,
      d.status as status_depois,
      (
        row(a.categoria, a.dre_grupo, a.status, a.entra_dre)
          is distinct from
        row(d.categoria, d.dre_grupo, d.status, d.entra_dre)
      ) as classificacao_mudou,
      a.fornecedor is distinct from d.fornecedor as rotulo_mudou
    from antes a
    full join depois d
      on d.origem = a.origem
     and d.raw_id = a.raw_id
  )
  select
    count(*),
    count(*) filter (where c.manual),
    count(*) filter (where not c.manual and c.classificacao_mudou),
    count(*) filter (where c.rotulo_mudou),
    count(*) filter (where c.classificacao_mudou or c.rotulo_mudou),
    coalesce(sum(c.valor) filter (
      where (c.classificacao_mudou or c.rotulo_mudou) and c.valor > 0
    ), 0),
    coalesce(abs(sum(c.valor) filter (
      where (c.classificacao_mudou or c.rotulo_mudou) and c.valor < 0
    )), 0),
    min(c.data_caixa) filter (where c.classificacao_mudou or c.rotulo_mudou),
    max(c.data_caixa) filter (where c.classificacao_mudou or c.rotulo_mudou)
  into
    v_correspondencias,
    v_ajustes_manuais,
    v_classificacoes,
    v_rotulos,
    v_impactadas,
    v_entradas,
    v_saidas,
    v_data_min,
    v_data_max
  from comparacao c;

  with antes as (
    select *
    from jsonb_to_recordset(v_antes) as x(
      origem text,
      raw_id text,
      data_caixa date,
      valor numeric,
      categoria text,
      dre_grupo text,
      status text,
      entra_dre boolean,
      fornecedor text,
      manual boolean,
      fonte_token text,
      ajuste_token text
    )
  ),
  depois as (
    select *
    from jsonb_to_recordset(v_depois) as x(
      origem text,
      raw_id text,
      data_caixa date,
      valor numeric,
      categoria text,
      dre_grupo text,
      status text,
      entra_dre boolean,
      fornecedor text,
      manual boolean,
      fonte_token text,
      ajuste_token text
    )
  ),
  agrupado as (
    select
      coalesce(a.categoria, 'Sem categoria') as categoria_antes,
      coalesce(d.categoria, 'Sem categoria') as categoria_depois,
      coalesce(a.status, 'sem status') as status_antes,
      coalesce(d.status, 'sem status') as status_depois,
      count(*) as quantidade
    from antes a
    join depois d
      on d.origem = a.origem
     and d.raw_id = a.raw_id
    where not coalesce(a.manual, false)
      and row(a.categoria, a.dre_grupo, a.status, a.entra_dre)
        is distinct from
          row(d.categoria, d.dre_grupo, d.status, d.entra_dre)
    group by a.categoria, d.categoria, a.status, d.status
  )
  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'categoria_antes', g.categoria_antes,
        'categoria_depois', g.categoria_depois,
        'status_antes', g.status_antes,
        'status_depois', g.status_depois,
        'quantidade', g.quantidade
      ) order by g.quantidade desc, g.categoria_antes, g.categoria_depois
    ),
    '[]'::jsonb
  )
  into v_transicoes
  from agrupado g;

  return jsonb_build_object(
    'regra_id', v_regra.id,
    'qtd_correspondencias', v_correspondencias,
    'qtd_ajustes_manuais', v_ajustes_manuais,
    'qtd_classificacao_alterada', v_classificacoes,
    'qtd_rotulo_alterado', v_rotulos,
    'qtd_impactadas', v_impactadas,
    'entradas_afetadas', v_entradas,
    'saidas_afetadas', v_saidas,
    'data_min', v_data_min,
    'data_max', v_data_max,
    'transicoes', v_transicoes,
    'impacto_token', md5(
      jsonb_build_array(
        v_token_atual,
        v_fornecedor,
        p_categoria,
        p_ativo,
        v_antes,
        v_depois
      )::text
    ),
    'historico_consolidado_alterado', false
  );
end;
$function$;

create or replace function public.salvar_regra_de_para(
  p_id bigint,
  p_fornecedor text,
  p_categoria text,
  p_ativo boolean,
  p_estado_token_esperado text,
  p_impacto_token_esperado text
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $function$
declare
  v_regra public.de_para%rowtype;
  v_nova public.de_para%rowtype;
  v_fornecedor text := nullif(btrim(p_fornecedor), '');
  v_token_atual text;
  v_previa jsonb;
begin
  if not public.usuario_pode_acessar_pagina('gerenciador_de_para.html') then
    raise exception using errcode = '42501', message = 'Acesso nao autorizado.';
  end if;

  if p_id is null
     or p_ativo is null
     or p_estado_token_esperado is null
     or p_impacto_token_esperado is null then
    raise exception using errcode = '22023', message = 'Estado da regra incompleto.';
  end if;

  if v_fornecedor is null or char_length(v_fornecedor) > 120 then
    raise exception using errcode = '22023',
      message = 'O nome de exibicao e obrigatorio e deve ter ate 120 caracteres.';
  end if;

  if not exists (
    select 1 from public.categoria_dre c where c.categoria = p_categoria
  ) then
    raise exception using errcode = '22023', message = 'Categoria invalida.';
  end if;

  -- A confirmacao recalcula a mesma fotografia. Importacoes ou ajustes feitos
  -- depois da previa invalidam o token e exigem nova revisao na tela.
  v_previa := public.prever_alteracao_de_para(
    p_id,
    v_fornecedor,
    p_categoria,
    p_ativo,
    p_estado_token_esperado
  );

  if v_previa ->> 'impacto_token' is distinct from p_impacto_token_esperado then
    raise exception using errcode = '40001',
      message = 'O impacto mudou desde a previa. Revise os dados novamente antes de confirmar.';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(58000002::bigint);

  select d.*
  into v_regra
  from public.de_para d
  where d.id = p_id
  for update;

  if not found then
    raise exception using errcode = 'P0002', message = 'Regra De/Para nao encontrada.';
  end if;

  v_token_atual := private.token_estado_de_para(
    v_regra.id,
    v_regra.chave_tipo,
    v_regra.chave_valor,
    v_regra.fornecedor,
    v_regra.categoria,
    v_regra.ativo,
    v_regra.atualizado_em
  );

  if v_token_atual is distinct from p_estado_token_esperado then
    raise exception using errcode = '40001',
      message = 'Esta regra mudou desde que a tela foi carregada. Atualize a lista e tente novamente.';
  end if;

  if row(v_regra.fornecedor, v_regra.categoria, v_regra.ativo)
       is not distinct from row(v_fornecedor, p_categoria, p_ativo) then
    raise exception using errcode = '22023', message = 'Nenhuma alteracao foi informada.';
  end if;

  perform pg_catalog.set_config('sirfisher.de_para_contexto', 'gerenciador', true);

  update public.de_para
  set fornecedor = v_fornecedor,
      categoria = p_categoria,
      ativo = p_ativo,
      atualizado_em = clock_timestamp()
  where id = v_regra.id
  returning * into v_nova;

  perform private.agendar_refresh_classificacoes(current_date);

  return jsonb_build_object(
    'id', v_nova.id,
    'estado_token', private.token_estado_de_para(
      v_nova.id,
      v_nova.chave_tipo,
      v_nova.chave_valor,
      v_nova.fornecedor,
      v_nova.categoria,
      v_nova.ativo,
      v_nova.atualizado_em
    )
  );
end;
$function$;

create or replace function private.desfazer_evento_de_para(
  p_historico_id bigint
)
returns bigint
language plpgsql
security definer
set search_path = pg_catalog, public
as $function$
declare
  v_evento private.de_para_historico%rowtype;
  v_atual public.de_para%rowtype;
  v_existe_atual boolean := false;
begin
  if p_historico_id is null then
    raise exception using errcode = '22023', message = 'Alteracao invalida.';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(58000002::bigint);

  select h.*
  into v_evento
  from private.de_para_historico h
  where h.id = p_historico_id
  for update;

  if not found then
    raise exception using errcode = 'P0002', message = 'Alteracao nao encontrada.';
  end if;

  if v_evento.desfeito_em is not null then
    raise exception using errcode = '55000', message = 'Esta alteracao ja foi desfeita.';
  end if;

  if v_evento.alterado_por is null or v_evento.origem_acao = 'sistema' then
    raise exception using errcode = '42501',
      message = 'Alteracoes tecnicas do sistema nao podem ser desfeitas por esta rotina.';
  end if;

  if exists (
    select 1
    from private.de_para_historico posterior
    where posterior.chave_tipo = v_evento.chave_tipo
      and posterior.chave_valor = v_evento.chave_valor
      and posterior.id > v_evento.id
      and posterior.desfeito_em is null
  ) then
    raise exception using errcode = '55000',
      message = 'Existe uma alteracao posterior ativa para esta regra.';
  end if;

  select d.*
  into v_atual
  from public.de_para d
  where d.id = v_evento.regra_id
  for update;
  v_existe_atual := found;

  if v_evento.existia_depois then
    if not v_existe_atual
       or row(v_atual.chave_tipo, v_atual.chave_valor, v_atual.fornecedor, v_atual.categoria, v_atual.ativo)
         is distinct from
          row(v_evento.chave_tipo, v_evento.chave_valor, v_evento.fornecedor_depois, v_evento.categoria_depois, v_evento.ativo_depois) then
      raise exception using errcode = '40001',
        message = 'O estado atual da regra nao corresponde mais a esta alteracao.';
    end if;
  elsif v_existe_atual then
    raise exception using errcode = '40001',
      message = 'A regra foi recriada depois desta alteracao.';
  end if;

  perform pg_catalog.set_config('sirfisher.de_para_contexto', 'desfazer', true);

  if v_evento.existia_antes then
    if v_existe_atual then
      update public.de_para
      set fornecedor = v_evento.fornecedor_antes,
          categoria = v_evento.categoria_antes,
          ativo = v_evento.ativo_antes,
          atualizado_em = v_evento.atualizado_em_antes
      where id = v_evento.regra_id;
    else
      insert into public.de_para (
        id,
        chave_tipo,
        chave_valor,
        fornecedor,
        categoria,
        ativo,
        atualizado_em
      ) values (
        v_evento.regra_id,
        v_evento.chave_tipo,
        v_evento.chave_valor,
        v_evento.fornecedor_antes,
        v_evento.categoria_antes,
        v_evento.ativo_antes,
        v_evento.atualizado_em_antes
      );
    end if;
  elsif v_existe_atual then
    -- Desfazer a criacao restaura a inexistencia exata. Esta e a unica
    -- exclusao do fluxo e ocorre sob lock, vinculada ao evento auditado.
    delete from public.de_para
    where id = v_evento.regra_id;
  end if;

  update private.de_para_historico
  set desfeito_por = auth.uid(),
      desfeito_em = clock_timestamp()
  where id = v_evento.id;

  perform private.agendar_refresh_classificacoes(current_date);

  return v_evento.regra_id;
end;
$function$;

revoke all privileges on function private.desfazer_evento_de_para(bigint)
  from public, anon, authenticated;

create or replace function public.desfazer_regra_de_para(
  p_historico_id bigint
)
returns bigint
language plpgsql
security definer
set search_path = pg_catalog, public
as $function$
begin
  if not public.usuario_pode_acessar_pagina('gerenciador_de_para.html') then
    raise exception using errcode = '42501', message = 'Acesso nao autorizado.';
  end if;

  return private.desfazer_evento_de_para(p_historico_id);
end;
$function$;

-- A fila de excecoes continua responsavel por criar/reclassificar uma chave,
-- agora passando pela mesma auditoria e pelo refresh assincrono.
create or replace function public.classificar_excecao(
  p_chave_tipo text,
  p_chave_valor text,
  p_fornecedor text,
  p_categoria text
)
returns bigint
language plpgsql
security definer
set search_path = pg_catalog, public
as $function$
declare
  v_id bigint;
  v_chave_valor text := btrim(p_chave_valor);
  v_fornecedor text := coalesce(nullif(btrim(p_fornecedor), ''), btrim(p_chave_valor));
  v_existente public.de_para%rowtype;
  v_existe boolean := false;
begin
  if not public.usuario_pode_acessar_pagina('classificar_excecoes.html') then
    raise exception using errcode = '42501', message = 'Acesso nao autorizado.';
  end if;

  if p_chave_tipo is null
     or p_chave_tipo not in ('nome', 'cnpj')
     or v_chave_valor is null
     or v_chave_valor = '' then
    raise exception using errcode = '22023', message = 'Chave de classificacao invalida.';
  end if;

  if not exists (
    select 1 from public.categoria_dre c where c.categoria = p_categoria
  ) then
    raise exception using errcode = '22023', message = 'Categoria invalida.';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(58000002::bigint);

  select d.*
  into v_existente
  from public.de_para d
  where d.chave_tipo = p_chave_tipo
    and d.chave_valor = v_chave_valor
  for update;
  v_existe := found;

  -- Uma resposta repetida da mesma classificacao e idempotente. Qualquer
  -- mudanca em regra ativa pertence ao gerenciador e exige previa/token.
  if v_existe and v_existente.ativo then
    if row(v_existente.fornecedor, v_existente.categoria)
         is not distinct from row(v_fornecedor, p_categoria) then
      return v_existente.id;
    end if;

    raise exception using errcode = '42501',
      message = 'Esta regra ja esta ativa. Use o Gerenciador De/Para para altera-la.';
  end if;

  if not exists (
    select 1
    from public.excecoes e
    where e.chave_tipo = p_chave_tipo
      and e.chave_valor = v_chave_valor
  ) then
    raise exception using errcode = '42501',
      message = 'Esta chave nao esta mais na fila de excecoes. Atualize a pagina antes de salvar.';
  end if;

  perform pg_catalog.set_config('sirfisher.de_para_contexto', 'classificar_excecoes', true);

  insert into public.de_para (
    chave_tipo,
    chave_valor,
    fornecedor,
    categoria,
    ativo,
    atualizado_em
  ) values (
    p_chave_tipo,
    v_chave_valor,
    v_fornecedor,
    p_categoria,
    true,
    clock_timestamp()
  )
  on conflict (chave_tipo, chave_valor) do update
    set fornecedor = excluded.fornecedor,
        categoria = excluded.categoria,
        ativo = true,
        atualizado_em = clock_timestamp()
  returning id into v_id;

  perform private.agendar_refresh_classificacoes(current_date);

  return v_id;
end;
$function$;

create or replace function public.corrigir_classificacao(
  p_tipo text,
  p_id bigint,
  p_categoria text
)
returns void
language plpgsql
security definer
set search_path = pg_catalog, public
as $function$
declare
  v_afetadas integer;
begin
  if not coalesce(
    (p_tipo = 'excecao' and public.usuario_pode_acessar_pagina('gerenciador_de_para.html'))
    or
    (p_tipo = 'individual' and public.usuario_pode_acessar_pagina('analise_individual.html')),
    false
  ) then
    raise exception using errcode = '42501', message = 'Acesso nao autorizado.';
  end if;

  if not exists (
    select 1 from public.categoria_dre c where c.categoria = p_categoria
  ) then
    raise exception using errcode = '22023', message = 'Categoria invalida.';
  end if;

  if p_tipo = 'excecao' then
    raise exception using errcode = '0A000',
      message = 'Use o Gerenciador De/Para para alterar regras por fornecedor.';
  elsif p_tipo = 'individual' then
    update public.ajuste_manual
    set categoria = p_categoria,
        criado_em = clock_timestamp()
    where id = p_id;
  else
    raise exception using errcode = '22023', message = 'Tipo de classificacao invalido.';
  end if;

  get diagnostics v_afetadas = row_count;
  if v_afetadas = 0 then
    raise exception using errcode = 'P0002', message = 'Classificacao nao encontrada.';
  end if;

  perform private.agendar_refresh_classificacoes(current_date);
end;
$function$;

create or replace function public.desfazer_classificacao(
  p_tipo text,
  p_id bigint
)
returns void
language plpgsql
security definer
set search_path = pg_catalog, public
as $function$
declare
  v_afetadas integer;
  v_historico_id bigint;
  v_pode_gerenciar boolean := public.usuario_pode_acessar_pagina('gerenciador_de_para.html');
begin
  if not coalesce(
    (p_tipo = 'excecao' and (
      v_pode_gerenciar
      or public.usuario_pode_acessar_pagina('classificar_excecoes.html')
    ))
    or
    (p_tipo = 'individual' and public.usuario_pode_acessar_pagina('analise_individual.html')),
    false
  ) then
    raise exception using errcode = '42501', message = 'Acesso nao autorizado.';
  end if;

  if p_tipo = 'excecao' then
    select h.id
    into v_historico_id
    from private.de_para_historico h
    where h.regra_id = p_id
      and h.desfeito_em is null
      and h.origem_acao = 'classificar_excecoes'
      and h.alterado_por = auth.uid()
      and h.alterado_em >= clock_timestamp() - interval '10 minutes'
    order by h.id desc
    limit 1;

    if v_historico_id is not null then
      perform private.desfazer_evento_de_para(v_historico_id);
      return;
    end if;

    raise exception using errcode = '42501',
      message = 'O prazo do desfazer imediato terminou. Use o Gerenciador De/Para.';
  elsif p_tipo = 'individual' then
    delete from public.ajuste_manual where id = p_id;
  else
    raise exception using errcode = '22023', message = 'Tipo de classificacao invalido.';
  end if;

  if p_tipo = 'individual' then
    get diagnostics v_afetadas = row_count;
    if v_afetadas = 0 then
      raise exception using errcode = 'P0002', message = 'Classificacao nao encontrada.';
    end if;
  end if;

  perform private.agendar_refresh_classificacoes(current_date);
end;
$function$;

create or replace view public.app_gerenciador_de_para_historico
with (security_barrier = true, security_invoker = false) as
select
  h.id,
  h.regra_id,
  h.chave_tipo,
  h.chave_valor,
  h.acao,
  h.origem_acao,
  h.existia_antes,
  h.fornecedor_antes,
  h.categoria_antes,
  h.ativo_antes,
  h.existia_depois,
  h.fornecedor_depois,
  h.categoria_depois,
  h.ativo_depois,
  private.nome_exibicao_usuario(h.alterado_por) as alterado_por_nome,
  h.alterado_em,
  h.desfeito_em is not null as desfeita,
  posterior.tem_posterior_ativa,
  h.desfeito_em is null
    and not posterior.tem_posterior_ativa
    and (
      (h.existia_depois and atual.id is not null
        and atual.chave_tipo = h.chave_tipo
        and atual.chave_valor = h.chave_valor
        and atual.fornecedor is not distinct from h.fornecedor_depois
        and atual.categoria is not distinct from h.categoria_depois
        and atual.ativo is not distinct from h.ativo_depois)
      or
      (not h.existia_depois and atual.id is null)
    ) as eh_estado_atual,
  h.desfeito_em is null
    and not posterior.tem_posterior_ativa
    and h.alterado_por is not null
    and h.origem_acao <> 'sistema'
    and (
      (h.existia_depois and atual.id is not null
        and atual.chave_tipo = h.chave_tipo
        and atual.chave_valor = h.chave_valor
        and atual.fornecedor is not distinct from h.fornecedor_depois
        and atual.categoria is not distinct from h.categoria_depois
        and atual.ativo is not distinct from h.ativo_depois)
      or
      (not h.existia_depois and atual.id is null)
    ) as pode_desfazer,
  private.nome_exibicao_usuario(h.desfeito_por) as desfeito_por_nome,
  h.desfeito_em
from private.de_para_historico h
left join public.de_para atual
  on atual.id = h.regra_id
left join lateral (
  select exists (
    select 1
    from private.de_para_historico seguinte
    where seguinte.chave_tipo = h.chave_tipo
      and seguinte.chave_valor = h.chave_valor
      and seguinte.id > h.id
      and seguinte.desfeito_em is null
  ) as tem_posterior_ativa
) posterior on true
where public.usuario_pode_acessar_pagina('gerenciador_de_para.html');

comment on view public.app_gerenciador_de_para_historico is
  'Historico protegido do De/Para; desfazer e liberado apenas para o ultimo estado ainda compativel.';

revoke all privileges on public.app_gerenciador_de_para_historico
  from public, anon, authenticated;
grant select on public.app_gerenciador_de_para_historico to authenticated;

-- A mesma lista de categorias atende as filas antigas, a revisao diaria e o
-- novo gerenciador, respeitando a permissao independente de cada pagina.
create or replace view public.app_categoria_dre
with (security_barrier = true, security_invoker = false) as
select categoria, dre_grupo, natureza
from public.categoria_dre
where public.usuario_pode_acessar_alguma_pagina(array[
  'analise_individual.html',
  'classificar_excecoes.html',
  'transacoes_dia.html',
  'gerenciador_de_para.html'
]::text[]);

revoke all privileges on public.app_categoria_dre
  from public, anon, authenticated;
grant select on public.app_categoria_dre to authenticated;

revoke all privileges on function public.listar_regras_de_para(
  text, text, text, text, integer, integer
) from public, anon, authenticated;
revoke all privileges on function public.prever_alteracao_de_para(
  bigint, text, text, boolean, text
) from public, anon, authenticated;
revoke all privileges on function public.salvar_regra_de_para(
  bigint, text, text, boolean, text, text
) from public, anon, authenticated;
revoke all privileges on function public.desfazer_regra_de_para(bigint)
  from public, anon, authenticated;
revoke all privileges on function public.classificar_excecao(text, text, text, text)
  from public, anon, authenticated;
revoke all privileges on function public.corrigir_classificacao(text, bigint, text)
  from public, anon, authenticated;
revoke all privileges on function public.desfazer_classificacao(text, bigint)
  from public, anon, authenticated;

grant execute on function public.listar_regras_de_para(
  text, text, text, text, integer, integer
) to authenticated;
grant execute on function public.prever_alteracao_de_para(
  bigint, text, text, boolean, text
) to authenticated;
grant execute on function public.salvar_regra_de_para(
  bigint, text, text, boolean, text, text
) to authenticated;
grant execute on function public.desfazer_regra_de_para(bigint)
  to authenticated;
grant execute on function public.classificar_excecao(text, text, text, text)
  to authenticated;
grant execute on function public.corrigir_classificacao(text, bigint, text)
  to authenticated;
grant execute on function public.desfazer_classificacao(text, bigint)
  to authenticated;

insert into public.pagina_permissao (pagina, papeis)
values ('gerenciador_de_para.html', array['socio'])
on conflict (pagina) do nothing;

commit;
