-- =====================================================================
-- Revisao diaria e auditavel das classificacoes por transacao
-- =====================================================================
--
-- Problema:
--   as rotinas atuais mostram apenas fornecedores sem regra ou transacoes
--   enviadas para analise individual. Nao existe uma leitura completa por dia
--   que explique a classificacao final e permita substituir somente a
--   categoria de um lancamento sem alterar o dado importado.
--
-- Solucao:
--   - view protegida sobre fato_financeiro, com origem da classificacao;
--   - historico append-only com autor e estados anterior/posterior;
--   - RPCs dedicadas para classificar, restaurar a base e desfazer;
--   - verificacao otimista para impedir que uma tela antiga sobrescreva uma
--     alteracao mais recente;
--   - refresh dos paineis pela fila assincrona ja existente.
--
-- Riscos controlados:
--   a categoria muda indicadores financeiros derivados. O ajuste continua
--   restrito a public.ajuste_manual; valor, data, origem e tabelas raw nunca
--   sao editados. O estado aparece imediatamente na view normal, enquanto as
--   materialized views sao atualizadas em segundo plano.
-- =====================================================================

begin;

create table if not exists private.transacao_classificacao_historico (
  id bigint generated by default as identity primary key,
  origem text not null,
  raw_id bigint not null,
  data_caixa date not null,
  valor numeric,
  contraparte_nome text,
  acao text not null check (acao in ('classificar', 'restaurar_automatica')),
  categoria_final_anterior text,
  categoria_final_nova text,
  ajuste_anterior text,
  ajuste_anterior_em timestamptz,
  ajuste_anterior_observacao text,
  ajuste_novo text,
  ajuste_novo_em timestamptz,
  ajuste_novo_observacao text,
  alterado_por uuid not null,
  alterado_em timestamptz not null default now(),
  desfeito_por uuid,
  desfeito_em timestamptz,
  check ((desfeito_por is null) = (desfeito_em is null)),
  check ((ajuste_anterior is null) = (ajuste_anterior_em is null)),
  check ((ajuste_novo is null) = (ajuste_novo_em is null))
);

create index if not exists ix_transacao_classificacao_historico_dia
  on private.transacao_classificacao_historico (data_caixa, alterado_em desc);

create index if not exists ix_transacao_classificacao_historico_transacao
  on private.transacao_classificacao_historico
  (origem, raw_id, alterado_em desc);

create index if not exists ix_conciliacao_decisao_estorno_ativo_a
  on public.conciliacao_contabil_decisao (origem_a, raw_id_a)
  where desfeito_em is null and decisao = 'estorno_confirmado';

create index if not exists ix_conciliacao_decisao_estorno_ativo_b
  on public.conciliacao_contabil_decisao (origem_b, raw_id_b)
  where desfeito_em is null and decisao = 'estorno_confirmado';

-- A decisao de estorno e a dona temporaria dos dois ajustes. Triggers
-- diferidos permitem que confirmar/desfazer a conciliacao altere decisao e
-- ajustes na mesma transacao, mas rejeitam qualquer estado final no qual uma
-- decisao ativa nao esteja acompanhada por duas categorias "estornado".
create or replace function private.validar_ponta_estorno_confirmado(
  p_origem text,
  p_raw_id bigint
)
returns void
language plpgsql
security definer
set search_path = pg_catalog, public
as $function$
begin
  if p_origem is null or p_raw_id is null then
    return;
  end if;

  if exists (
    select 1
    from public.conciliacao_contabil_decisao d
    where d.desfeito_em is null
      and d.decisao = 'estorno_confirmado'
      and (
        (d.origem_a = p_origem and d.raw_id_a = p_raw_id)
        or
        (d.origem_b = p_origem and d.raw_id_b = p_raw_id)
      )
  ) and not exists (
    select 1
    from public.ajuste_manual a
    where a.origem = p_origem
      and a.raw_id = p_raw_id
      and a.categoria = 'estornado'
  ) then
    raise exception using errcode = '55000',
      message = 'Esta transacao pertence a um estorno confirmado. Desfaca a decisao na conciliacao contabil antes de alterar a classificacao.';
  end if;
end;
$function$;

create or replace function private.validar_ajuste_estorno_confirmado()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public
as $function$
begin
  if tg_op = 'DELETE' then
    perform private.validar_ponta_estorno_confirmado(old.origem, old.raw_id);
  elsif tg_op = 'INSERT' then
    perform private.validar_ponta_estorno_confirmado(new.origem, new.raw_id);
  else
    perform private.validar_ponta_estorno_confirmado(old.origem, old.raw_id);
    if (new.origem, new.raw_id) is distinct from (old.origem, old.raw_id) then
      perform private.validar_ponta_estorno_confirmado(new.origem, new.raw_id);
    end if;
  end if;

  return null;
end;
$function$;

create or replace function private.validar_decisao_estorno_confirmado()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public
as $function$
declare
  v_decisao public.conciliacao_contabil_decisao%rowtype;
  v_id bigint;
begin
  if tg_op = 'DELETE' then
    v_id := old.id;
  else
    v_id := new.id;
  end if;

  select *
  into v_decisao
  from public.conciliacao_contabil_decisao d
  where d.id = v_id
    and d.desfeito_em is null
    and d.decisao = 'estorno_confirmado';

  if found then
    perform private.validar_ponta_estorno_confirmado(
      v_decisao.origem_a,
      v_decisao.raw_id_a
    );
    perform private.validar_ponta_estorno_confirmado(
      v_decisao.origem_b,
      v_decisao.raw_id_b
    );
  end if;

  return null;
end;
$function$;

drop trigger if exists ct_ajuste_estorno_confirmado
  on public.ajuste_manual;
create constraint trigger ct_ajuste_estorno_confirmado
after insert or update or delete on public.ajuste_manual
deferrable initially deferred
for each row execute function private.validar_ajuste_estorno_confirmado();

drop trigger if exists ct_decisao_estorno_confirmado
  on public.conciliacao_contabil_decisao;
create constraint trigger ct_decisao_estorno_confirmado
after insert or update or delete on public.conciliacao_contabil_decisao
deferrable initially deferred
for each row execute function private.validar_decisao_estorno_confirmado();

-- Nao corrige dados financeiros silenciosamente. Se um fluxo antigo ja tiver
-- quebrado uma decisao ativa, a migration para e informa que o caso precisa de
-- revisao consciente antes de instalar a nova garantia.
do $migration$
declare
  v_inconsistentes bigint;
begin
  select count(*)
  into v_inconsistentes
  from public.conciliacao_contabil_decisao d
  where d.desfeito_em is null
    and d.decisao = 'estorno_confirmado'
    and (
      not exists (
        select 1
        from public.ajuste_manual a
        where a.origem = d.origem_a
          and a.raw_id = d.raw_id_a
          and a.categoria = 'estornado'
      )
      or not exists (
        select 1
        from public.ajuste_manual a
        where a.origem = d.origem_b
          and a.raw_id = d.raw_id_b
          and a.categoria = 'estornado'
      )
    );

  if v_inconsistentes > 0 then
    raise exception using errcode = '55000',
      message = format(
        'Existem %s decisoes ativas de estorno sem as duas pontas classificadas como estornado. Revise esses casos antes de aplicar esta migration.',
        v_inconsistentes
      );
  end if;
end;
$migration$;

revoke all privileges on function private.validar_ponta_estorno_confirmado(
  text, bigint
) from public, anon, authenticated;
revoke all privileges on function private.validar_ajuste_estorno_confirmado()
  from public, anon, authenticated;
revoke all privileges on function private.validar_decisao_estorno_confirmado()
  from public, anon, authenticated;

-- Todos os front-ends escrevem por RPC SECURITY DEFINER. Retirar DML direto
-- fecha o ultimo caminho que contornava as validacoes transacionais.
revoke insert, update, delete on table public.ajuste_manual
  from authenticated;
revoke usage, select on sequence public.ajuste_manual_id_seq
  from authenticated;
drop policy if exists ajuste_auth_ins on public.ajuste_manual;
drop policy if exists ajuste_auth_upd on public.ajuste_manual;

alter table private.transacao_classificacao_historico enable row level security;
revoke all privileges on private.transacao_classificacao_historico
  from public, anon, authenticated;

comment on table private.transacao_classificacao_historico is
  'Historico protegido e reversivel dos ajustes individuais feitos pela revisao diaria; sem acesso direto pela Data API.';

create or replace view public.app_transacoes_dia
with (security_barrier = true, security_invoker = false) as
select
  f.origem,
  f.raw_id,
  f.empresa,
  f.unidade,
  f.data_caixa,
  f.data_competencia,
  f.movimentacao,
  f.tipo,
  f.valor,
  f.contraparte_nome,
  f.fornecedor,
  f.categoria,
  f.dre_grupo,
  f.status,
  f.natureza,
  f.entra_dre,
  a.categoria as ajuste_atual,
  a.criado_em as ajuste_em,
  case
    when a.id is null then null
    else md5((a.observacao is null)::text || ':' || coalesce(a.observacao, ''))
  end as ajuste_observacao_token,
  decisao.id as conciliacao_decisao_id,
  decisao.ano_mes as conciliacao_ano_mes,
  decisao.id is not null as classificacao_bloqueada,
  case
    when a.id is not null then 'manual'
    when f.categoria is null or f.status in ('analise', 'excecao') then 'pendente'
    when f.origem = 'historico' then 'base_historica'
    else 'automatica'
  end as classificacao_origem
from public.fato_financeiro f
left join public.ajuste_manual a
  on a.origem = f.origem
 and a.raw_id = f.raw_id
left join lateral (
  select d.id, to_char(d.data_a, 'YYYY-MM') as ano_mes
  from public.conciliacao_contabil_decisao d
  where d.desfeito_em is null
    and d.decisao = 'estorno_confirmado'
    and (
      (d.origem_a = f.origem and d.raw_id_a = f.raw_id)
      or
      (d.origem_b = f.origem and d.raw_id_b = f.raw_id)
    )
  order by d.id desc
  limit 1
) decisao on true
where f.data_caixa is not null
  and f.raw_id is not null
  and public.usuario_pode_acessar_pagina('transacoes_dia.html');

comment on view public.app_transacoes_dia is
  'Lancamentos financeiros por dia com classificacao final e indicador de ajuste manual; leitura protegida da rotina de revisao diaria.';

revoke all privileges on public.app_transacoes_dia
  from public, anon, authenticated;
grant select on public.app_transacoes_dia to authenticated;

create or replace view public.app_transacoes_dia_historico
with (security_barrier = true, security_invoker = false) as
select
  h.id,
  h.origem,
  h.raw_id,
  h.data_caixa,
  h.valor,
  h.contraparte_nome,
  h.acao,
  h.categoria_final_anterior,
  h.categoria_final_nova,
  h.ajuste_anterior,
  h.ajuste_novo,
  private.nome_exibicao_usuario(h.alterado_por) as alterado_por_nome,
  h.alterado_em,
  h.desfeito_em is not null as desfeita,
  posterior.tem_posterior_ativa,
  h.desfeito_em is null
    and not posterior.tem_posterior_ativa
    and atual.categoria is not distinct from h.ajuste_novo
    and atual.criado_em is not distinct from h.ajuste_novo_em
    and atual.observacao is not distinct from h.ajuste_novo_observacao
    as eh_estado_atual,
  decisao.id is not null as bloqueada_conciliacao,
  h.desfeito_em is null
    and not posterior.tem_posterior_ativa
    and atual.categoria is not distinct from h.ajuste_novo
    and atual.criado_em is not distinct from h.ajuste_novo_em
    and atual.observacao is not distinct from h.ajuste_novo_observacao
    and decisao.id is null
    as pode_desfazer,
  private.nome_exibicao_usuario(h.desfeito_por) as desfeito_por_nome,
  h.desfeito_em
from private.transacao_classificacao_historico h
left join public.ajuste_manual atual
  on atual.origem = h.origem
 and atual.raw_id = h.raw_id
left join lateral (
  select exists (
    select 1
    from private.transacao_classificacao_historico seguinte
    where seguinte.origem = h.origem
      and seguinte.raw_id = h.raw_id
      and seguinte.desfeito_em is null
      and seguinte.id > h.id
  ) as tem_posterior_ativa
) posterior on true
left join lateral (
  select d.id
  from public.conciliacao_contabil_decisao d
  where d.desfeito_em is null
    and d.decisao = 'estorno_confirmado'
    and (
      (d.origem_a = h.origem and d.raw_id_a = h.raw_id)
      or
      (d.origem_b = h.origem and d.raw_id_b = h.raw_id)
    )
  order by d.id desc
  limit 1
) decisao on true
where public.usuario_pode_acessar_pagina('transacoes_dia.html');

comment on view public.app_transacoes_dia_historico is
  'Historico protegido das classificacoes da revisao diaria, com autor e indicacao segura de desfazer.';

revoke all privileges on public.app_transacoes_dia_historico
  from public, anon, authenticated;
grant select on public.app_transacoes_dia_historico to authenticated;

-- A mesma lista de categorias atende as duas filas antigas e a nova rotina.
create or replace view public.app_categoria_dre
with (security_barrier = true, security_invoker = false) as
select categoria, dre_grupo, natureza
from public.categoria_dre
where public.usuario_pode_acessar_alguma_pagina(array[
  'analise_individual.html',
  'classificar_excecoes.html',
  'transacoes_dia.html'
]::text[]);

revoke all privileges on public.app_categoria_dre
  from public, anon, authenticated;
grant select on public.app_categoria_dre to authenticated;

-- Ajustes criados pela conciliacao pertencem aquela rotina e nao aparecem
-- como classificacoes individuais editaveis na tela antiga.
create or replace view public.app_classificacoes_recentes
with (security_barrier = true, security_invoker = false) as
select
  'excecao'::text as tipo,
  d.id::bigint as id,
  coalesce(d.fornecedor, d.chave_valor) as titulo,
  case d.chave_tipo when 'cnpj' then 'Regra por CNPJ' else 'Regra por nome' end as detalhe,
  d.categoria,
  c.natureza,
  d.atualizado_em as quando,
  null::date as data_lancamento,
  null::numeric as valor
from public.de_para d
left join public.categoria_dre c on c.categoria = d.categoria
where d.ativo
  and public.usuario_pode_acessar_pagina('classificar_excecoes.html')

union all

select
  'individual'::text as tipo,
  a.id::bigint as id,
  coalesce(f.contraparte_nome, f.fornecedor, a.origem || ' #' || a.raw_id::text) as titulo,
  'Transacao individual'::text as detalhe,
  a.categoria,
  f.natureza,
  a.criado_em as quando,
  f.data_caixa as data_lancamento,
  f.valor
from public.ajuste_manual a
left join public.fato_financeiro f
  on f.origem = a.origem and f.raw_id = a.raw_id
where public.usuario_pode_acessar_pagina('analise_individual.html')
  and not exists (
    select 1
    from public.conciliacao_contabil_decisao d
    where d.desfeito_em is null
      and d.decisao = 'estorno_confirmado'
      and (
        (d.origem_a = a.origem and d.raw_id_a = a.raw_id)
        or
        (d.origem_b = a.origem and d.raw_id_b = a.raw_id)
      )
  );

revoke all privileges on public.app_classificacoes_recentes
  from public, anon, authenticated;
grant select on public.app_classificacoes_recentes to authenticated;

-- Varias correcoes feitas em sequencia compartilham uma unica tarefa pendente,
-- evitando executar o refresh completo das materialized views a cada clique.
create or replace function private.agendar_refresh_classificacoes(
  p_data date
)
returns bigint
language plpgsql
security definer
set search_path = pg_catalog, pg_temp
as $function$
declare
  v_id bigint;
begin
  if p_data is null then
    raise exception using errcode = '22023', message = 'Data do refresh invalida.';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(58000001::bigint);

  select f.id
  into v_id
  from private.fila_recalculo_saldo f
  where f.situacao = 'pendente'
    and f.somente_refresh
  order by f.id
  for update skip locked
  limit 1;

  if v_id is not null then
    update private.fila_recalculo_saldo
    set data_min = least(data_min, p_data),
        data_max = greatest(data_max, p_data),
        mensagem = 'Atualizacao do painel solicitada por classificacoes manuais.'
    where id = v_id;
  else
    insert into private.fila_recalculo_saldo (
      data_min,
      data_max,
      somente_refresh,
      mensagem
    ) values (
      p_data,
      p_data,
      true,
      'Atualizacao do painel solicitada por classificacoes manuais.'
    ) returning id into v_id;
  end if;

  perform cron.schedule(
    'sirfisher-processar-recalculo-saldo',
    '5 seconds',
    'select private.processar_fila_recalculo_saldo();'
  );

  return v_id;
end;
$function$;

revoke all privileges on function private.agendar_refresh_classificacoes(date)
  from public, anon, authenticated;

create or replace function public.salvar_classificacao_transacao_dia(
  p_origem text,
  p_raw_id bigint,
  p_categoria text,
  p_categoria_atual_esperada text,
  p_ajuste_atual_esperado text,
  p_ajuste_em_esperado timestamptz,
  p_ajuste_observacao_token_esperado text
)
returns bigint
language plpgsql
security definer
set search_path = pg_catalog, public
as $function$
declare
  v_data_caixa date;
  v_valor numeric;
  v_contraparte_nome text;
  v_categoria_final text;
  v_ajuste_anterior text;
  v_ajuste_anterior_em timestamptz;
  v_ajuste_anterior_observacao text;
  v_ajuste_observacao_token text;
  v_ajuste_novo_em timestamptz;
  v_ajuste_novo_observacao text;
  v_agora timestamptz := clock_timestamp();
  v_id bigint;
begin
  if not public.usuario_pode_acessar_pagina('transacoes_dia.html') then
    raise exception using errcode = '42501', message = 'Acesso nao autorizado.';
  end if;

  if p_origem is null or btrim(p_origem) = '' or p_raw_id is null then
    raise exception using errcode = '22023', message = 'Transacao invalida.';
  end if;

  if p_categoria is null
     or p_categoria = 'ANALISAR INDIVIDUAL'
     or not exists (
    select 1
    from public.categoria_dre c
    where c.categoria = p_categoria
  ) then
    raise exception using errcode = '22023', message = 'Categoria invalida.';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(p_origem || ':' || p_raw_id::text, 20260810)
  );

  select
    f.data_caixa,
    f.valor,
    f.contraparte_nome,
    f.categoria,
    a.categoria,
    a.criado_em,
    a.observacao
  into
    v_data_caixa,
    v_valor,
    v_contraparte_nome,
    v_categoria_final,
    v_ajuste_anterior,
    v_ajuste_anterior_em,
    v_ajuste_anterior_observacao
  from public.fato_financeiro f
  left join public.ajuste_manual a
    on a.origem = f.origem
   and a.raw_id = f.raw_id
  where f.origem = p_origem
    and f.raw_id = p_raw_id;

  if not found then
    raise exception using errcode = 'P0002', message = 'Transacao nao encontrada.';
  end if;

  if v_data_caixa is null then
    raise exception using errcode = '22023', message = 'Transacao sem data de caixa.';
  end if;

  v_ajuste_observacao_token := case
    when v_ajuste_anterior is null then null
    else md5(
      (v_ajuste_anterior_observacao is null)::text
      || ':'
      || coalesce(v_ajuste_anterior_observacao, '')
    )
  end;

  if exists (
    select 1
    from public.conciliacao_contabil_decisao d
    where d.desfeito_em is null
      and d.decisao = 'estorno_confirmado'
      and (
        (d.origem_a = p_origem and d.raw_id_a = p_raw_id)
        or
        (d.origem_b = p_origem and d.raw_id_b = p_raw_id)
      )
  ) then
    raise exception using errcode = '55000',
      message = 'Esta transacao pertence a um estorno confirmado. Desfaca a decisao na conciliacao contabil antes de reclassificar.';
  end if;

  if v_categoria_final is distinct from p_categoria_atual_esperada
     or v_ajuste_anterior is distinct from p_ajuste_atual_esperado
     or v_ajuste_anterior_em is distinct from p_ajuste_em_esperado
     or v_ajuste_observacao_token is distinct from p_ajuste_observacao_token_esperado then
    raise exception using errcode = '40001',
      message = 'A transacao foi alterada por outra acao. Atualize a tela antes de salvar.';
  end if;

  if v_ajuste_anterior is not distinct from p_categoria then
    raise exception using errcode = '22023', message = 'A transacao ja possui esse ajuste manual.';
  end if;

  if v_ajuste_anterior is null and v_categoria_final is not distinct from p_categoria then
    raise exception using errcode = '22023', message = 'A transacao ja possui essa classificacao na base.';
  end if;

  if v_ajuste_anterior is null then
    insert into public.ajuste_manual (origem, raw_id, categoria, criado_em)
    values (p_origem, p_raw_id, p_categoria, v_agora)
    on conflict (origem, raw_id) do nothing
    returning criado_em, observacao
    into v_ajuste_novo_em, v_ajuste_novo_observacao;

    if not found then
      raise exception using errcode = '40001',
        message = 'A transacao foi alterada por outra acao. Atualize a tela antes de salvar.';
    end if;
  else
    update public.ajuste_manual
    set categoria = p_categoria,
        criado_em = v_agora
    where origem = p_origem
      and raw_id = p_raw_id
      and categoria is not distinct from v_ajuste_anterior
      and criado_em is not distinct from v_ajuste_anterior_em
      and observacao is not distinct from v_ajuste_anterior_observacao
    returning criado_em, observacao
    into v_ajuste_novo_em, v_ajuste_novo_observacao;

    if not found then
      raise exception using errcode = '40001',
        message = 'A transacao foi alterada por outra acao. Atualize a tela antes de salvar.';
    end if;
  end if;

  insert into private.transacao_classificacao_historico (
    origem,
    raw_id,
    data_caixa,
    valor,
    contraparte_nome,
    acao,
    categoria_final_anterior,
    categoria_final_nova,
    ajuste_anterior,
    ajuste_anterior_em,
    ajuste_anterior_observacao,
    ajuste_novo,
    ajuste_novo_em,
    ajuste_novo_observacao,
    alterado_por,
    alterado_em
  ) values (
    p_origem,
    p_raw_id,
    v_data_caixa,
    v_valor,
    v_contraparte_nome,
    'classificar',
    v_categoria_final,
    p_categoria,
    v_ajuste_anterior,
    v_ajuste_anterior_em,
    v_ajuste_anterior_observacao,
    p_categoria,
    v_ajuste_novo_em,
    v_ajuste_novo_observacao,
    auth.uid(),
    v_agora
  ) returning id into v_id;

  perform private.agendar_refresh_classificacoes(v_data_caixa);

  return v_id;
end;
$function$;

create or replace function public.restaurar_classificacao_transacao_dia(
  p_origem text,
  p_raw_id bigint,
  p_categoria_atual_esperada text,
  p_ajuste_atual_esperado text,
  p_ajuste_em_esperado timestamptz,
  p_ajuste_observacao_token_esperado text
)
returns bigint
language plpgsql
security definer
set search_path = pg_catalog, public
as $function$
declare
  v_data_caixa date;
  v_valor numeric;
  v_contraparte_nome text;
  v_categoria_final text;
  v_categoria_restaurada text;
  v_ajuste_anterior text;
  v_ajuste_anterior_em timestamptz;
  v_ajuste_anterior_observacao text;
  v_ajuste_observacao_token text;
  v_agora timestamptz := clock_timestamp();
  v_id bigint;
begin
  if not public.usuario_pode_acessar_pagina('transacoes_dia.html') then
    raise exception using errcode = '42501', message = 'Acesso nao autorizado.';
  end if;

  if p_origem is null or btrim(p_origem) = '' or p_raw_id is null then
    raise exception using errcode = '22023', message = 'Transacao invalida.';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(p_origem || ':' || p_raw_id::text, 20260810)
  );

  select
    f.data_caixa,
    f.valor,
    f.contraparte_nome,
    f.categoria,
    a.categoria,
    a.criado_em,
    a.observacao
  into
    v_data_caixa,
    v_valor,
    v_contraparte_nome,
    v_categoria_final,
    v_ajuste_anterior,
    v_ajuste_anterior_em,
    v_ajuste_anterior_observacao
  from public.fato_financeiro f
  left join public.ajuste_manual a
    on a.origem = f.origem
   and a.raw_id = f.raw_id
  where f.origem = p_origem
    and f.raw_id = p_raw_id;

  if not found then
    raise exception using errcode = 'P0002', message = 'Transacao nao encontrada.';
  end if;

  if v_data_caixa is null then
    raise exception using errcode = '22023', message = 'Transacao sem data de caixa.';
  end if;

  v_ajuste_observacao_token := case
    when v_ajuste_anterior is null then null
    else md5(
      (v_ajuste_anterior_observacao is null)::text
      || ':'
      || coalesce(v_ajuste_anterior_observacao, '')
    )
  end;

  if exists (
    select 1
    from public.conciliacao_contabil_decisao d
    where d.desfeito_em is null
      and d.decisao = 'estorno_confirmado'
      and (
        (d.origem_a = p_origem and d.raw_id_a = p_raw_id)
        or
        (d.origem_b = p_origem and d.raw_id_b = p_raw_id)
      )
  ) then
    raise exception using errcode = '55000',
      message = 'Esta transacao pertence a um estorno confirmado. Desfaca a decisao na conciliacao contabil antes de restaurar.';
  end if;

  if v_categoria_final is distinct from p_categoria_atual_esperada
     or v_ajuste_anterior is distinct from p_ajuste_atual_esperado
     or v_ajuste_anterior_em is distinct from p_ajuste_em_esperado
     or v_ajuste_observacao_token is distinct from p_ajuste_observacao_token_esperado then
    raise exception using errcode = '40001',
      message = 'A transacao foi alterada por outra acao. Atualize a tela antes de restaurar.';
  end if;

  if v_ajuste_anterior is null then
    raise exception using errcode = '22023', message = 'A transacao nao possui ajuste manual.';
  end if;

  delete from public.ajuste_manual
  where origem = p_origem
    and raw_id = p_raw_id
    and categoria is not distinct from v_ajuste_anterior
    and criado_em is not distinct from v_ajuste_anterior_em
    and observacao is not distinct from v_ajuste_anterior_observacao;

  if not found then
    raise exception using errcode = '40001',
      message = 'A transacao foi alterada por outra acao. Atualize a tela antes de restaurar.';
  end if;

  select f.categoria
  into v_categoria_restaurada
  from public.fato_financeiro f
  where f.origem = p_origem
    and f.raw_id = p_raw_id;

  if not found then
    raise exception using errcode = 'P0002', message = 'Transacao nao encontrada apos restaurar.';
  end if;

  insert into private.transacao_classificacao_historico (
    origem,
    raw_id,
    data_caixa,
    valor,
    contraparte_nome,
    acao,
    categoria_final_anterior,
    categoria_final_nova,
    ajuste_anterior,
    ajuste_anterior_em,
    ajuste_anterior_observacao,
    ajuste_novo,
    ajuste_novo_em,
    ajuste_novo_observacao,
    alterado_por,
    alterado_em
  ) values (
    p_origem,
    p_raw_id,
    v_data_caixa,
    v_valor,
    v_contraparte_nome,
    'restaurar_automatica',
    v_categoria_final,
    v_categoria_restaurada,
    v_ajuste_anterior,
    v_ajuste_anterior_em,
    v_ajuste_anterior_observacao,
    null,
    null,
    null,
    auth.uid(),
    v_agora
  ) returning id into v_id;

  perform private.agendar_refresh_classificacoes(v_data_caixa);

  return v_id;
end;
$function$;

create or replace function public.desfazer_classificacao_transacao_dia(
  p_historico_id bigint
)
returns void
language plpgsql
security definer
set search_path = pg_catalog, public
as $function$
declare
  v_evento private.transacao_classificacao_historico%rowtype;
  v_ajuste_atual text;
  v_ajuste_atual_em timestamptz;
  v_ajuste_atual_observacao text;
  v_agora timestamptz := clock_timestamp();
begin
  if not public.usuario_pode_acessar_pagina('transacoes_dia.html') then
    raise exception using errcode = '42501', message = 'Acesso nao autorizado.';
  end if;

  select *
  into v_evento
  from private.transacao_classificacao_historico
  where id = p_historico_id
    and desfeito_em is null
  for update;

  if not found then
    raise exception using errcode = 'P0002', message = 'Alteracao ativa nao encontrada.';
  end if;

  if exists (
    select 1
    from private.transacao_classificacao_historico posterior
    where posterior.origem = v_evento.origem
      and posterior.raw_id = v_evento.raw_id
      and posterior.desfeito_em is null
      and posterior.id > v_evento.id
  ) then
    raise exception using errcode = '40001',
      message = 'Existe uma alteracao posterior nesta transacao. Desfaca a mais recente primeiro.';
  end if;

  if exists (
    select 1
    from public.conciliacao_contabil_decisao d
    where d.desfeito_em is null
      and d.decisao = 'estorno_confirmado'
      and (
        (d.origem_a = v_evento.origem and d.raw_id_a = v_evento.raw_id)
        or
        (d.origem_b = v_evento.origem and d.raw_id_b = v_evento.raw_id)
      )
  ) then
    raise exception using errcode = '55000',
      message = 'Esta transacao pertence a um estorno confirmado. Desfaca a decisao na conciliacao contabil antes.';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(v_evento.origem || ':' || v_evento.raw_id::text, 20260810)
  );

  select a.categoria, a.criado_em, a.observacao
  into v_ajuste_atual, v_ajuste_atual_em, v_ajuste_atual_observacao
  from public.ajuste_manual a
  where a.origem = v_evento.origem
    and a.raw_id = v_evento.raw_id;

  if v_ajuste_atual is distinct from v_evento.ajuste_novo
     or v_ajuste_atual_em is distinct from v_evento.ajuste_novo_em
     or v_ajuste_atual_observacao is distinct from v_evento.ajuste_novo_observacao then
    raise exception using errcode = '40001',
      message = 'A classificacao mudou depois desta acao. Atualize a tela antes de desfazer.';
  end if;

  if v_evento.ajuste_anterior is null then
    delete from public.ajuste_manual
    where origem = v_evento.origem
      and raw_id = v_evento.raw_id
      and categoria is not distinct from v_evento.ajuste_novo
      and criado_em is not distinct from v_evento.ajuste_novo_em
      and observacao is not distinct from v_evento.ajuste_novo_observacao;

    if not found then
      raise exception using errcode = '40001',
        message = 'A classificacao mudou depois desta acao. Atualize a tela antes de desfazer.';
    end if;
  elsif v_evento.ajuste_novo is null then
    insert into public.ajuste_manual (
      origem,
      raw_id,
      categoria,
      criado_em,
      observacao
    )
    values (
      v_evento.origem,
      v_evento.raw_id,
      v_evento.ajuste_anterior,
      v_evento.ajuste_anterior_em,
      v_evento.ajuste_anterior_observacao
    )
    on conflict (origem, raw_id) do nothing;

    if not found then
      raise exception using errcode = '40001',
        message = 'A classificacao mudou depois desta acao. Atualize a tela antes de desfazer.';
    end if;
  else
    update public.ajuste_manual
    set categoria = v_evento.ajuste_anterior,
        criado_em = v_evento.ajuste_anterior_em,
        observacao = v_evento.ajuste_anterior_observacao
    where origem = v_evento.origem
      and raw_id = v_evento.raw_id
      and categoria is not distinct from v_evento.ajuste_novo
      and criado_em is not distinct from v_evento.ajuste_novo_em
      and observacao is not distinct from v_evento.ajuste_novo_observacao;

    if not found then
      raise exception using errcode = '40001',
        message = 'A classificacao mudou depois desta acao. Atualize a tela antes de desfazer.';
    end if;
  end if;

  update private.transacao_classificacao_historico
  set desfeito_por = auth.uid(),
      desfeito_em = v_agora
  where id = v_evento.id;

  perform private.agendar_refresh_classificacoes(v_evento.data_caixa);
end;
$function$;

revoke all privileges on function public.salvar_classificacao_transacao_dia(
  text, bigint, text, text, text, timestamptz, text
) from public, anon, authenticated;
revoke all privileges on function public.restaurar_classificacao_transacao_dia(
  text, bigint, text, text, timestamptz, text
) from public, anon, authenticated;
revoke all privileges on function public.desfazer_classificacao_transacao_dia(bigint)
  from public, anon, authenticated;

grant execute on function public.salvar_classificacao_transacao_dia(
  text, bigint, text, text, text, timestamptz, text
) to authenticated;
grant execute on function public.restaurar_classificacao_transacao_dia(
  text, bigint, text, text, timestamptz, text
) to authenticated;
grant execute on function public.desfazer_classificacao_transacao_dia(bigint)
  to authenticated;

insert into public.pagina_permissao (pagina, papeis)
values ('transacoes_dia.html', array['socio'])
on conflict (pagina) do nothing;

commit;
