-- =====================================================================
-- Acoes transacionais para a rotina de conciliacao contabil
-- =====================================================================
--
-- Permite confirmar as duas pontas como estorno ou registrar que um par nao
-- e relacionado. Toda decisao guarda autor/data e pode ser desfeita. Confirmar
-- estorno grava dois ajustes manuais na mesma transacao de banco; se qualquer
-- etapa falhar, nenhuma ponta e alterada.
-- =====================================================================

begin;

create table if not exists public.conciliacao_contabil_decisao (
  id bigint generated by default as identity primary key,
  chave_par text not null,
  origem_a text not null,
  raw_id_a bigint not null,
  origem_b text not null,
  raw_id_b bigint not null,
  data_a date not null,
  data_b date not null,
  valor_a numeric not null,
  valor_b numeric not null,
  contraparte_a text,
  contraparte_b text,
  categoria_anterior_a text,
  categoria_anterior_b text,
  ajuste_anterior_a text,
  ajuste_anterior_b text,
  decisao text not null check (decisao in ('estorno_confirmado', 'nao_relacionados')),
  decidido_por uuid not null,
  decidido_em timestamptz not null default now(),
  desfeito_por uuid,
  desfeito_em timestamptz,
  check ((desfeito_por is null) = (desfeito_em is null))
);

create unique index if not exists ux_conciliacao_contabil_decisao_ativa
  on public.conciliacao_contabil_decisao (chave_par)
  where desfeito_em is null;

create index if not exists ix_conciliacao_contabil_decisao_periodo
  on public.conciliacao_contabil_decisao (data_a, decidido_em desc);

alter table public.conciliacao_contabil_decisao enable row level security;
revoke all on public.conciliacao_contabil_decisao from public, anon, authenticated;

comment on table public.conciliacao_contabil_decisao is
  'Historico auditavel das decisoes sobre pares de possivel estorno; acesso somente por views e RPCs protegidas.';

create or replace function public.decidir_conciliacao_contabil(
  p_origem_a text,
  p_raw_id_a bigint,
  p_origem_b text,
  p_raw_id_b bigint,
  p_decisao text
)
returns bigint
language plpgsql
security definer
set search_path = pg_catalog, public
as $function$
declare
  v_a record;
  v_b record;
  v_chave_a text;
  v_chave_b text;
  v_chave_par text;
  v_ajuste_anterior_a text;
  v_ajuste_anterior_b text;
  v_id bigint;
  v_encontrou_a boolean;
  v_encontrou_b boolean;
begin
  if not public.usuario_pode_acessar_pagina('conciliacao_contabil.html') then
    raise exception using errcode = '42501', message = 'Acesso nao autorizado.';
  end if;

  if p_decisao not in ('estorno_confirmado', 'nao_relacionados') then
    raise exception using errcode = '22023', message = 'Decisao invalida.';
  end if;

  if (p_origem_a, p_raw_id_a) = (p_origem_b, p_raw_id_b) then
    raise exception using errcode = '22023', message = 'As duas pontas precisam ser diferentes.';
  end if;

  select * into v_a
  from public.mv_conciliacao_contabil
  where origem = p_origem_a and raw_id = p_raw_id_a;
  v_encontrou_a := found;

  select * into v_b
  from public.mv_conciliacao_contabil
  where origem = p_origem_b and raw_id = p_raw_id_b;
  v_encontrou_b := found;

  if not v_encontrou_a or not v_encontrou_b then
    raise exception using errcode = '22023', message = 'Uma das pontas nao foi encontrada.';
  end if;

  if v_a.nivel_reversao is null or v_b.nivel_reversao is null
     or (v_a.par_origem, v_a.par_raw_id) is distinct from (p_origem_b, p_raw_id_b)
     or (v_b.par_origem, v_b.par_raw_id) is distinct from (p_origem_a, p_raw_id_a) then
    raise exception using errcode = '22023', message = 'O par informado nao e um possivel estorno vigente.';
  end if;

  v_chave_a := p_origem_a || ':' || p_raw_id_a::text;
  v_chave_b := p_origem_b || ':' || p_raw_id_b::text;
  v_chave_par := least(v_chave_a, v_chave_b) || '|' || greatest(v_chave_a, v_chave_b);

  if exists (
    select 1
    from public.conciliacao_contabil_decisao d
    where d.chave_par = v_chave_par
      and d.desfeito_em is null
  ) then
    raise exception using errcode = '23505', message = 'Este par ja possui uma decisao ativa.';
  end if;

  select a.categoria into v_ajuste_anterior_a
  from public.ajuste_manual a
  where a.origem = p_origem_a and a.raw_id = p_raw_id_a;

  select a.categoria into v_ajuste_anterior_b
  from public.ajuste_manual a
  where a.origem = p_origem_b and a.raw_id = p_raw_id_b;

  insert into public.conciliacao_contabil_decisao (
    chave_par,
    origem_a, raw_id_a, origem_b, raw_id_b,
    data_a, data_b, valor_a, valor_b,
    contraparte_a, contraparte_b,
    categoria_anterior_a, categoria_anterior_b,
    ajuste_anterior_a, ajuste_anterior_b,
    decisao, decidido_por
  ) values (
    v_chave_par,
    p_origem_a, p_raw_id_a, p_origem_b, p_raw_id_b,
    v_a.data_caixa, v_b.data_caixa, v_a.valor, v_b.valor,
    v_a.contraparte_nome, v_b.contraparte_nome,
    v_a.categoria, v_b.categoria,
    v_ajuste_anterior_a, v_ajuste_anterior_b,
    p_decisao, auth.uid()
  ) returning id into v_id;

  if p_decisao = 'estorno_confirmado' then
    insert into public.ajuste_manual (origem, raw_id, categoria, criado_em)
    values
      (p_origem_a, p_raw_id_a, 'estornado', now()),
      (p_origem_b, p_raw_id_b, 'estornado', now())
    on conflict (origem, raw_id) do update
      set categoria = excluded.categoria,
          criado_em = now();

    set local statement_timeout = 0;
    refresh materialized view public.mv_conciliacao_contabil;
  end if;

  return v_id;
end;
$function$;

create or replace function public.desfazer_decisao_conciliacao_contabil(
  p_decisao_id bigint
)
returns void
language plpgsql
security definer
set search_path = pg_catalog, public
as $function$
declare
  v_decisao public.conciliacao_contabil_decisao%rowtype;
begin
  if not public.usuario_pode_acessar_pagina('conciliacao_contabil.html') then
    raise exception using errcode = '42501', message = 'Acesso nao autorizado.';
  end if;

  select * into v_decisao
  from public.conciliacao_contabil_decisao
  where id = p_decisao_id
    and desfeito_em is null
  for update;

  if not found then
    raise exception using errcode = 'P0002', message = 'Decisao ativa nao encontrada.';
  end if;

  if v_decisao.decisao = 'estorno_confirmado' then
    if not exists (
      select 1 from public.ajuste_manual
      where origem = v_decisao.origem_a
        and raw_id = v_decisao.raw_id_a
        and categoria = 'estornado'
    ) or not exists (
      select 1 from public.ajuste_manual
      where origem = v_decisao.origem_b
        and raw_id = v_decisao.raw_id_b
        and categoria = 'estornado'
    ) then
      raise exception using errcode = '40001',
        message = 'Uma das pontas foi alterada depois da confirmacao; revise antes de desfazer.';
    end if;

    if v_decisao.ajuste_anterior_a is null then
      delete from public.ajuste_manual
      where origem = v_decisao.origem_a and raw_id = v_decisao.raw_id_a;
    else
      update public.ajuste_manual
      set categoria = v_decisao.ajuste_anterior_a,
          criado_em = now()
      where origem = v_decisao.origem_a and raw_id = v_decisao.raw_id_a;
    end if;

    if v_decisao.ajuste_anterior_b is null then
      delete from public.ajuste_manual
      where origem = v_decisao.origem_b and raw_id = v_decisao.raw_id_b;
    else
      update public.ajuste_manual
      set categoria = v_decisao.ajuste_anterior_b,
          criado_em = now()
      where origem = v_decisao.origem_b and raw_id = v_decisao.raw_id_b;
    end if;
  end if;

  update public.conciliacao_contabil_decisao
  set desfeito_por = auth.uid(),
      desfeito_em = now()
  where id = v_decisao.id;

  if v_decisao.decisao = 'estorno_confirmado' then
    set local statement_timeout = 0;
    refresh materialized view public.mv_conciliacao_contabil;
  end if;
end;
$function$;

revoke all on function public.decidir_conciliacao_contabil(text, bigint, text, bigint, text)
  from public, anon;
revoke all on function public.desfazer_decisao_conciliacao_contabil(bigint)
  from public, anon;
grant execute on function public.decidir_conciliacao_contabil(text, bigint, text, bigint, text)
  to authenticated;
grant execute on function public.desfazer_decisao_conciliacao_contabil(bigint)
  to authenticated;

drop view if exists public.app_conciliacao_contabil_decisoes;
drop view if exists public.app_conciliacao_contabil_resumo_mensal;
drop view if exists public.app_conciliacao_contabil;

create or replace view public.app_conciliacao_contabil
with (security_barrier = true, security_invoker = false) as
select
  m.origem,
  m.raw_id,
  m.data_caixa,
  m.data_hora,
  m.ano_mes,
  m.valor,
  m.tipo,
  m.categoria,
  m.dre_grupo,
  m.contraparte_nome,
  m.fornecedor,
  m.espera_zerar,
  case
    when d.decisao = 'estorno_confirmado' then 'estorno_confirmado'
    when d.decisao = 'nao_relacionados' then 'descartado'
    else m.status_conciliacao
  end as status_conciliacao,
  m.qtd_candidatos,
  m.par_origem,
  m.par_raw_id,
  m.par_data,
  m.par_data_hora,
  m.par_valor,
  m.par_categoria,
  m.par_contraparte,
  m.dias_diferenca,
  m.nivel_reversao,
  m.evidencia_reversao,
  m.minutos_intervalo,
  m.contraparte_confere,
  m.possui_horario,
  d.id as decisao_id,
  d.decisao,
  d.decidido_em,
  m.atualizado_em
from public.mv_conciliacao_contabil m
left join public.conciliacao_contabil_decisao d
  on d.desfeito_em is null
 and d.chave_par = case
   when m.par_origem is null or m.par_raw_id is null then null
   else least(m.origem || ':' || m.raw_id::text,
              m.par_origem || ':' || m.par_raw_id::text)
        || '|'
        || greatest(m.origem || ':' || m.raw_id::text,
                    m.par_origem || ':' || m.par_raw_id::text)
 end
where public.usuario_pode_acessar_pagina('conciliacao_contabil.html');

create or replace view public.app_conciliacao_contabil_resumo_mensal
with (security_barrier = true, security_invoker = false) as
select
  m.ano_mes,
  case
    when d.decisao = 'estorno_confirmado' then 'estorno_confirmado'
    when d.decisao = 'nao_relacionados' then 'descartado'
    else m.status_conciliacao
  end as status_conciliacao,
  count(*)::integer as qtd,
  round(sum(m.valor), 2) as total,
  round(coalesce(sum(m.valor) filter (where m.valor > 0), 0), 2) as creditos,
  round(coalesce(sum(m.valor) filter (where m.valor < 0), 0), 2) as debitos,
  max(m.atualizado_em) as atualizado_em
from public.mv_conciliacao_contabil m
left join public.conciliacao_contabil_decisao d
  on d.desfeito_em is null
 and d.chave_par = case
   when m.par_origem is null or m.par_raw_id is null then null
   else least(m.origem || ':' || m.raw_id::text,
              m.par_origem || ':' || m.par_raw_id::text)
        || '|'
        || greatest(m.origem || ':' || m.raw_id::text,
                    m.par_origem || ':' || m.par_raw_id::text)
 end
where public.usuario_pode_acessar_pagina('conciliacao_contabil.html')
group by
  m.ano_mes,
  case
    when d.decisao = 'estorno_confirmado' then 'estorno_confirmado'
    when d.decisao = 'nao_relacionados' then 'descartado'
    else m.status_conciliacao
  end;

create or replace view public.app_conciliacao_contabil_decisoes
with (security_barrier = true, security_invoker = false) as
select
  d.id,
  to_char(d.data_a, 'YYYY-MM') as ano_mes,
  d.decisao,
  d.origem_a,
  d.raw_id_a,
  d.origem_b,
  d.raw_id_b,
  d.data_a,
  d.data_b,
  d.valor_a,
  d.valor_b,
  d.contraparte_a,
  d.contraparte_b,
  d.categoria_anterior_a,
  d.categoria_anterior_b,
  private.nome_exibicao_usuario(d.decidido_por) as decidido_por_nome,
  d.decidido_em,
  d.desfeito_em is null as ativa,
  private.nome_exibicao_usuario(d.desfeito_por) as desfeito_por_nome,
  d.desfeito_em
from public.conciliacao_contabil_decisao d
where public.usuario_pode_acessar_pagina('conciliacao_contabil.html');

comment on view public.app_conciliacao_contabil is
  'Detalhe protegido da conciliacao contabil com decisoes ativas aplicadas ao status.';
comment on view public.app_conciliacao_contabil_resumo_mensal is
  'Resumo mensal protegido da conciliacao contabil, incluindo pares resolvidos e descartados.';
comment on view public.app_conciliacao_contabil_decisoes is
  'Historico protegido e reversivel das decisoes tomadas na conciliacao contabil.';

revoke all on public.app_conciliacao_contabil from public, anon;
revoke all on public.app_conciliacao_contabil_resumo_mensal from public, anon;
revoke all on public.app_conciliacao_contabil_decisoes from public, anon;
grant select on public.app_conciliacao_contabil to authenticated;
grant select on public.app_conciliacao_contabil_resumo_mensal to authenticated;
grant select on public.app_conciliacao_contabil_decisoes to authenticated;

commit;
